name: app-state-diagram
safe: true
lsi: false

url: http://www.app-state-diagram.com/
title: app-state-diagram

markdown: kramdown
redcarpet:
  extensions: ["autolink", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]
highlighter: rouge
